In [4]:
import pandas as pd

In [5]:
df=pd.read_csv(r"/users/pawarbharath/downloads/drive/fortune1000.csv")

In [3]:
df

,Rank,Company,Sector,Industry,Location,Revenue,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
1,2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
2,3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
3,4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
4,5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
...,...,...,...,...,...,...,...,...
995,996,New York Community Bancorp,Financials,Commercial Banks,"Westbury, NY",1902,-47,3448
996,997,Portland General Electric,Energy,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
997,997,Portland General Electric,Energy,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
998,999,Wendy’s,"Hotels, Resturants & Leisure",Food Services,"Dublin, OH",1896,161,21200
999,1000,Briggs & Stratton,Industrials,Industrial Machinery,"Wauwatosa, WI",1895,46,5480

In [53]:
df.shape

(1000, 8)

In [19]:
industry=df.groupby('Industry')

In [86]:
len(industry)

73

In [89]:
df['Industry'].nunique()

73

In [17]:
industry.size().head(60)

Industry
Advertising, marketing                             2
Aerospace and Defense                             20
Airlines                                           9
Apparel                                           15
Automotive Retailing, Services                    10
Beverages                                          9
Building Materials, Glass                          7
Chemicals                                         30
Commercial Banks                                  28
Computer Peripherals                               4
Computer Software                                 14
Computers, Office Equipment                        7
Construction and Farm Machinery                    9
Diversified Financials                            15
Diversified Outsourcing Services                  14
Education                                          3
Electronics, Electrical Equip.                    13
Energy                                            14
Engineering, Construction                         14
Entertainment                                     18
Financial Data Services                           19
Food Consumer Products                            20
Food Production                                    9
Food Services                                     12
Food and Drug Stores                              15
Forest and Paper Products                          5
General Merchandisers                             10
Health Care: Insurance and Managed Care           11
Health Care: Medical Facilities                   14
Health Care: Pharmacy and Other Services          13
Home Equipment, Furnishings                       12
Homebuilders                                      12
Hotels, Casinos, Resorts                          13
Household and Personal Products                   13
Industrial Machinery                              23
Information Technology Services                   13
Insurance: Life, Health (Mutual)                  10
Insurance: Life, Health (stock)                   18
Insurance: Property and Casualty (Mutual)          7
Insurance: Property and Casualty (Stock)          28
Internet Services and Retailing                   15
Mail, Package, and Freight Delivery                2
Medical Products and Equipment                    16
Metals                                            14
Mining, Crude-Oil Production                      28
Miscellaneous                                     11
Motor Vehicles and Parts                          24
Network and Other Communications Equipment        14
Oil and Gas Equipment, Services                    9
Packaging, Containers                             16
Petroleum Refining                                17
Pharmaceuticals                                   15
Pipelines                                         12
Publishing, Printing                               7
Railroads                                          5
Real estate                                       15
Scientific,Photographic and Control Equipment     12
Securities                                        18
Semiconductors and Other Electronic Components    23
Specialty Retailers: Apparel                      18
dtype: int64

In [21]:
df.head(50)

,Rank,Company,Sector,Industry,Location,Revenue,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
1,2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
2,3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
3,4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
4,5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
5,6,UnitedHealth Group,Health Care,Health Care: Insurance and Managed Care,"Minnetonka, MN",157107,5813,200000
6,7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
7,8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
8,9,Ford Motor,Motor Vehicles & Parts,Motor Vehicles and Parts,"Dearborn, MI",149558,7373,199000
9,10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
10,11,General Electric,Industrials,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
11,12,AmerisourceBergen,Health Care,Wholesalers: Health Care,"Chesterbrook, PA",135962,-135,17000
12,13,Verizon,Telecommunications,Telecommunications,"New York, NY",131620,17879,177700
13,14,Chevron,Energy,Petroleum Refining,"San Ramon, CA",131118,4587,61500
14,15,Costco,Retailing,Specialty Retailers: Other,"Issaquah, WA",116199,2377,161000
15,16,Fannie Mae,Financials,Diversified Financials,"Washington, DC",110359,10954,7300
16,17,Kroger,Food and Drug Stores,Food and Drug Stores,"Cincinnati, OH",109830,2039,431000
17,18,Amazon.com,Technology,Internet Services and Retailing,"Seattle, WA",107006,596,230800
18,19,Walgreens Boots Alliance,Food and Drug Stores,Food and Drug Stores,"Deerfield, IL",103444,4220,302500
19,20,HP,Technology,"Computers, Office Equipment","Palo Alto, CA",103355,4554,287000
20,21,Cardinal Health,Health Care,Wholesalers: Health Care,"Dublin, OH",102531,1215,34500
21,22,Express Scripts Holding,Health Care,Health Care: Pharmacy and Other Services,"St. Louis, MO",101752,2476,25900
22,23,J.P. Morgan Chase,Financials,Commercial Banks,"New York, NY",101006,24442,234598
23,24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
24,25,Microsoft,Technology,Computer Software,"Redmond, WA",93580,12193,118000
25,26,Bank of America Corp.,Financials,Commercial Banks,"Charlotte, NC",93056,15888,213280
26,27,Wells Fargo,Financials,Commercial Banks,"San Francisco, CA",90033,22894,264700
27,28,Home Depot,Retailing,Specialty Retailers: Other,"Atlanta, GA",88519,7009,385000
28,29,Citigroup,Financials,Commercial Banks,"New York, NY",88275,17242,231000
29,30,Phillips 66,Energy,Petroleum Refining,"Houston, TX",87169,4227,14000
30,31,IBM,Technology,Information Technology Services,"Armonk, NY",82461,13190,411798
31,32,Valero Energy,Energy,Petroleum Refining,"San Antonio, TX",81824,3990,10103
32,33,Anthem,Health Care,Health Care: Insurance and Managed Care,"Indianapolis, IN",79157,2560,53000
33,34,Procter & Gamble,Household Products,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
34,35,State Farm Insurance Cos.,Financials,Insurance: Property and Casualty (Mutual),"Bloomington, IL",75697,6229,70425
35,36,Alphabet,Technology,Internet Services and Retailing,"Mountain View, CA",74989,16348,61814
36,37,Comcast,Telecommunications,Telecommunications,"Philadelphia, PA",74510,8163,153000
37,38,Target,Retailing,General Merchandisers,"Minneapolis, MN",73785,3363,341000
38,39,Johnson & Johnson,Health Care,Pharmaceuticals,"New Brunswick, NJ",70074,15409,127100
39,40,MetLife,Financials,"Insurance: Life, Health (stock)","New York, NY",69951,5310,69000
40,41,Archer Daniels Midland,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",67702,1849,32300
41,42,Marathon Petroleum,Energy,Petroleum Refining,"Findlay, OH",64566,2852,45440
42,43,Freddie Mac,Financials,Diversified Financials,"McLean, VA",63491,6376,5439
43,44,PepsiCo,"Food, Beverages & Tobacco",Food Consumer Products,"Purchase, NY",63056,5452,263000
44,45,United Technologies,Aerospace & Defense,Aerospace and Defense,"Farmington, CT",61047,7608,197200
45,46,Aetna,Health Care,Health Care: Insurance and Managed Care,"Hartford, CT",60337,2390,50100
46,47,Lowe’s,Retailing,Specialty Retailers: Other,"Mooresville, NC",59074,2546,225000
47,48,UPS,Transportation,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
48,49,AIG,Financials,Insurance: Property and Casualty (Stock),"New York, NY",58327,2196,66400
49,50,Prudential Financial,Financials,"Insurance: Life, Health (stock)","Newark, NJ",57119,5642,49384

In [20]:
industry.get_group('Petroleum Refining')['Revenue']

1      246204
13     131118
29      87169
31      81824
41      64566
97      28150
213     13238
216     13124
288      9787
393      6575
444      5762
568      4260
570      4213
731      3002
849      2470
952      2066
982      1944
Name: Revenue, dtype: int64

In [9]:
industry.get_group('General Merchandisers')

,Rank,Company,Sector,Industry,Location,Revenue,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
37,38,Target,Retailing,General Merchandisers,"Minneapolis, MN",73785,3363,341000
102,103,Macy’s,Retailing,General Merchandisers,"Cincinnati, OH",27079,1072,157500
110,111,Sears Holdings,Retailing,General Merchandisers,"Hoffman Estates, IL",25146,-1129,178000
138,139,Dollar General,Retailing,General Merchandisers,"Goodlettsville, TN",20369,1165,113400
144,145,Kohl’s,Retailing,General Merchandisers,"Menomonee Falls, WI",19204,673,86000
196,197,Nordstrom,Retailing,General Merchandisers,"Seattle, WA",14437,600,72500
227,228,J.C. Penney,Retailing,General Merchandisers,"Plano, TX",12625,-513,105000
379,380,Dillard’s,Retailing,General Merchandisers,"Little Rock, AR",6755,269,30600
772,773,Bon-Ton Stores,Retailing,General Merchandisers,"York, PA",2790,-57,24100

In [23]:
df[df['Industry']=='General Merchandisers']

,Rank,Company,Sector,Industry,Location,Revenue,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
37,38,Target,Retailing,General Merchandisers,"Minneapolis, MN",73785,3363,341000
102,103,Macy’s,Retailing,General Merchandisers,"Cincinnati, OH",27079,1072,157500
110,111,Sears Holdings,Retailing,General Merchandisers,"Hoffman Estates, IL",25146,-1129,178000
138,139,Dollar General,Retailing,General Merchandisers,"Goodlettsville, TN",20369,1165,113400
144,145,Kohl’s,Retailing,General Merchandisers,"Menomonee Falls, WI",19204,673,86000
196,197,Nordstrom,Retailing,General Merchandisers,"Seattle, WA",14437,600,72500
227,228,J.C. Penney,Retailing,General Merchandisers,"Plano, TX",12625,-513,105000
379,380,Dillard’s,Retailing,General Merchandisers,"Little Rock, AR",6755,269,30600
772,773,Bon-Ton Stores,Retailing,General Merchandisers,"York, PA",2790,-57,24100

In [83]:
sectors=df.groupby('Sector')

In [78]:
sectors['Profits'].sum()

Sector
Aerospace & Defense              28742
Apparel                           8236
Business Services                28227
Chemicals                        22628
Energy                          -73447
Engineering & Construction        5304
Financials                      260209
Food and Drug Stores             16759
Food, Beverages & Tobacco        51417
Health Care                     106114
Hotels, Resturants & Leisure     20697
Household Products               14428
Industrials                      20764
Materials                         4428
Media                            24347
Motor Vehicles & Parts           25898
Retailing                        47830
Technology                      180473
Telecommunications               48637
Transportation                   44169
Wholesalers                       8233
Name: Profits, dtype: int64

In [91]:
sectors[['Profits','Revenue']].mean()

                                  Profits       Revenue
Sector
Aerospace & Defense           1437.100000  17897.000000
Apparel                        549.066667   6397.866667
Business Services              553.470588   5337.156863
Chemicals                      754.266667   8129.900000
Energy                        -602.024590  12441.057377
Engineering & Construction     204.000000   5922.423077
Financials                    1872.007194  15950.784173
Food and Drug Stores          1117.266667  32251.266667
Food, Beverages & Tobacco     1195.744186  12929.465116
Health Care                   1414.853333  21529.426667
Hotels, Resturants & Leisure   827.880000   6781.840000
Household Products             515.285714   8383.464286
Industrials                    451.391304  10816.978261
Materials                      102.976744   6026.627907
Media                          973.880000   8830.560000
Motor Vehicles & Parts        1079.083333  20105.833333
Retailing                      597.875000  18313.450000
Technology                    1769.343137  13505.882353
Telecommunications            3242.466667  30788.933333
Transportation                1226.916667  11347.444444
Wholesalers                    205.825000  11120.000000

In [80]:
df['Employees'].mean()

33028.002

In [95]:
sectors[['Employees','Profits']].mean()

                                 Employees      Profits
Sector
Aerospace & Defense           48402.850000  1437.100000
Apparel                       23093.133333   549.066667
Business Services             26687.254902   553.470588
Chemicals                     15455.033333   754.266667
Energy                         9745.303279  -602.024590
Engineering & Construction    15642.615385   204.000000
Financials                    24172.287770  1872.007194
Food and Drug Stores          93026.533333  1117.266667
Food, Beverages & Tobacco     28177.488372  1195.744186
Health Care                   35710.520000  1414.853333
Hotels, Resturants & Leisure  99369.800000   827.880000
Household Products            23072.785714   515.285714
Industrials                   33591.934783   451.391304
Materials                     14840.069767   102.976744
Media                         22012.560000   973.880000
Motor Vehicles & Parts        45106.666667  1079.083333
Retailing                     77845.362500   597.875000
Technology                    35087.735294  1769.343137
Telecommunications            55497.866667  3242.466667
Transportation                42688.694444  1226.916667
Wholesalers                   13139.925000   205.825000

In [57]:
sectors.get_group('Retailing')['Profits'].sum()

47830

In [25]:
type(sectors)

pandas.core.groupby.generic.DataFrameGroupBy

In [29]:
sectors.size()

Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

In [30]:
industry=df.groupby('Industry')

In [98]:
india=df.groupby(['Sector','Industry'])

In [99]:
india.max()

                                                                   Rank  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                           987
Apparel             Apparel                                         917
Business Services   Advertising, marketing                          355
                    Diversified Outsourcing Services                869
                    Education                                       993
...                                                                 ...
Transportation      Trucking, Truck Leasing                         945
Wholesalers         Miscellaneous                                   315
                    Wholesalers: Diversified                        991
                    Wholesalers: Electronics and Office Equipment   685
                    Wholesalers: Food and Grocery                   351

                                                                                Company  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                                      Woodward
Apparel             Apparel                                        Wolverine World Wide
Business Services   Advertising, marketing                                Omnicom Group
                    Diversified Outsourcing Services                               West
                    Education                                           Graham Holdings
...                                                                                 ...
Transportation      Trucking, Truck Leasing                               YRC Worldwide
Wholesalers         Miscellaneous                                                Univar
                    Wholesalers: Diversified                        World Fuel Services
                    Wholesalers: Electronics and Office Equipment             Tech Data
                    Wholesalers: Food and Grocery                  United Natural Foods

                                                                                  Location  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                                      Wichita, KS
Apparel             Apparel                                              Winston-Salem, NC
Business Services   Advertising, marketing                                    New York, NY
                    Diversified Outsourcing Services                       San Leandro, CA
                    Education                                                  Phoenix, AZ
...                                                                                    ...
Transportation      Trucking, Truck Leasing                                Thomasville, NC
Wholesalers         Miscellaneous                                        Downers Grove, IL
                    Wholesalers: Diversified                                   Waltham, MA
                    Wholesalers: Electronics and Office Equipment                Tempe, AZ
                    Wholesalers: Food and Grocery                  South San Francisco, CA

                                                                   Revenue  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                            96114
Apparel             Apparel                                          30601
Business Services   Advertising, marketing                           15134
                    Diversified Outsourcing Services                 14329
                    Education                                         2984
...                                                                    ...
Transportation      Trucking, Truck Leasing                           6572
Wholesalers         Miscellaneous                                     8982
                    Wholesalers: Diversified                         30380
                    Wholesalers: Electronics and Office Equipment    43026
                    Wholesalers: Food and Grocery                    48681

                                                                   Profits  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                             7608
Apparel             Apparel                                           3273
Business Services   Advertising, marketing                            1094
                    Diversified Outsourcing Services                  1453
                    Education                                          140
...                                                                    ...
Transportation      Trucking, Truck Leasing                            427
Wholesalers         Miscellaneous                                       17
                    Wholesalers: Diversified                          1472
                    Wholesalers: Electronics and Office Equipment      572
                    Wholesalers: Food and Grocery                      687

                                                                   Employees
Sector              Industry
Aerospace & Defense Aerospace and Defense                             197200
Apparel             Apparel                                            65300
Business Services   Advertising, marketing                             74900
                    Diversified Outsourcing Services                  216500
                    Education                                          23400
...                                                                      ...
Transportation      Trucking, Truck Leasing                            33100
Wholesalers         Miscellaneous                                       9200
                    Wholesalers: Diversified                           39600
                    Wholesalers: Electronics and Office Equipment      78500
                    Wholesalers: Food and Grocery                      51700

[79 rows x 6 columns]

In [100]:
india.min()

                                                                   Rank  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                            24
Apparel             Apparel                                          91
Business Services   Advertising, marketing                          186
                    Diversified Outsourcing Services                199
                    Education                                       737
...                                                                 ...
Transportation      Trucking, Truck Leasing                         395
Wholesalers         Miscellaneous                                   315
                    Wholesalers: Diversified                         92
                    Wholesalers: Electronics and Office Equipment    64
                    Wholesalers: Food and Grocery                    57

                                                                                  Company  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                                   B/E Aerospace
Apparel             Apparel                                                      Carter’s
Business Services   Advertising, marketing                              Interpublic Group
                    Diversified Outsourcing Services                       ABM Industries
                    Education                                      Apollo Education Group
...                                                                                   ...
Transportation      Trucking, Truck Leasing                                        Amerco
Wholesalers         Miscellaneous                                                  Univar
                    Wholesalers: Diversified                                       Airgas
                    Wholesalers: Electronics and Office Equipment       Arrow Electronics
                    Wholesalers: Food and Grocery                       Core-Mark Holding

                                                                            Location  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                                 Berwyn, PA
Apparel             Apparel                                              Atlanta, GA
Business Services   Advertising, marketing                              New York, NY
                    Diversified Outsourcing Services                   Arlington, VA
                    Education                                          Arlington, VA
...                                                                              ...
Transportation      Trucking, Truck Leasing                           Fort Smith, AR
Wholesalers         Miscellaneous                                  Downers Grove, IL
                    Wholesalers: Diversified                             Atlanta, GA
                    Wholesalers: Electronics and Office Equipment     Centennial, CO
                    Wholesalers: Food and Grocery                   Byron Center, MI

                                                                   Revenue  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                             1923
Apparel             Apparel                                           2204
Business Services   Advertising, marketing                            7614
                    Diversified Outsourcing Services                  2383
                    Education                                         1910
...                                                                    ...
Transportation      Trucking, Truck Leasing                           2094
Wholesalers         Miscellaneous                                     8982
                    Wholesalers: Diversified                          1917
                    Wholesalers: Electronics and Office Equipment     3219
                    Wholesalers: Food and Grocery                     7652

                                                                   Profits  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                             -240
Apparel             Apparel                                             82
Business Services   Advertising, marketing                             455
                    Diversified Outsourcing Services                   -12
                    Education                                         -101
...                                                                    ...
Transportation      Trucking, Truck Leasing                              1
Wholesalers         Miscellaneous                                       17
                    Wholesalers: Diversified                          -502
                    Wholesalers: Electronics and Office Equipment      -44
                    Wholesalers: Food and Grocery                       52

                                                                   Employees
Sector              Industry
Aerospace & Defense Aerospace and Defense                               6955
Apparel             Apparel                                             5978
Business Services   Advertising, marketing                             49200
                    Diversified Outsourcing Services                    2400
                    Education                                          11585
...                                                                      ...
Transportation      Trucking, Truck Leasing                             1223
Wholesalers         Miscellaneous                                       9200
                    Wholesalers: Diversified                             500
                    Wholesalers: Electronics and Office Equipment       2000
                    Wholesalers: Food and Grocery                       6655

[79 rows x 6 columns]

In [62]:
industry.get_group('General Merchandisers')['Profits'].sum()

20137

In [51]:
industry.get_group('General Merchandisers')['Profits']

0      14694
37      3363
102     1072
110    -1129
138     1165
144      673
196      600
227     -513
379      269
772      -57
Name: Profits, dtype: int64

In [90]:
industry.size()

Industry
Advertising, marketing                            2
Aerospace and Defense                            20
Airlines                                          9
Apparel                                          15
Automotive Retailing, Services                   10
                                                 ..
Waste Management                                  5
Wholesalers: Diversified                         25
Wholesalers: Electronics and Office Equipment     8
Wholesalers: Food and Grocery                     6
Wholesalers: Health Care                          6
Length: 73, dtype: int64

In [41]:
industry.size().head(60)

Industry
Advertising, marketing                             2
Aerospace and Defense                             20
Airlines                                           9
Apparel                                           15
Automotive Retailing, Services                    10
Beverages                                          9
Building Materials, Glass                          7
Chemicals                                         30
Commercial Banks                                  28
Computer Peripherals                               4
Computer Software                                 14
Computers, Office Equipment                        7
Construction and Farm Machinery                    9
Diversified Financials                            15
Diversified Outsourcing Services                  14
Education                                          3
Electronics, Electrical Equip.                    13
Energy                                            14
Engineering, Construction                         14
Entertainment                                     18
Financial Data Services                           19
Food Consumer Products                            20
Food Production                                    9
Food Services                                     12
Food and Drug Stores                              15
Forest and Paper Products                          5
General Merchandisers                             10
Health Care: Insurance and Managed Care           11
Health Care: Medical Facilities                   14
Health Care: Pharmacy and Other Services          13
Home Equipment, Furnishings                       12
Homebuilders                                      12
Hotels, Casinos, Resorts                          13
Household and Personal Products                   13
Industrial Machinery                              23
Information Technology Services                   13
Insurance: Life, Health (Mutual)                  10
Insurance: Life, Health (stock)                   18
Insurance: Property and Casualty (Mutual)          7
Insurance: Property and Casualty (Stock)          28
Internet Services and Retailing                   15
Mail, Package, and Freight Delivery                2
Medical Products and Equipment                    16
Metals                                            14
Mining, Crude-Oil Production                      28
Miscellaneous                                     11
Motor Vehicles and Parts                          24
Network and Other Communications Equipment        14
Oil and Gas Equipment, Services                    9
Packaging, Containers                             16
Petroleum Refining                                17
Pharmaceuticals                                   15
Pipelines                                         12
Publishing, Printing                               7
Railroads                                          5
Real estate                                       15
Scientific,Photographic and Control Equipment     12
Securities                                        18
Semiconductors and Other Electronic Components    23
Specialty Retailers: Apparel                      18
dtype: int64

In [45]:
df['Industry'].unique()

array(['General Merchandisers', 'Petroleum Refining',
       'Computers, Office Equipment',
       'Insurance: Property and Casualty (Stock)',
       'Wholesalers: Health Care',
       'Health Care: Insurance and Managed Care', 'Food and Drug Stores',
       'Motor Vehicles and Parts', 'Telecommunications',
       'Industrial Machinery', 'Specialty Retailers: Other',
       'Diversified Financials', 'Internet Services and Retailing',
       'Health Care: Pharmacy and Other Services', 'Commercial Banks',
       'Aerospace and Defense', 'Computer Software',
       'Information Technology Services',
       'Household and Personal Products',
       'Insurance: Property and Casualty (Mutual)', 'Pharmaceuticals',
       'Insurance: Life, Health (stock)', 'Food Production',
       'Food Consumer Products', 'Mail, Package, and Freight Delivery',
       'Semiconductors and Other Electronic Components', 'Entertainment',
       'Network and Other Communications Equipment', 'Chemicals',
       'Wholesalers: Food and Grocery', 'Construction and Farm Machinery',
       'Insurance: Life, Health (Mutual)', 'Beverages',
       'Health Care: Medical Facilities',
       'Wholesalers: Electronics and Office Equipment', 'Pipelines',
       'Airlines', 'Electronics, Electrical Equip.',
       'Specialty Retailers: Apparel', 'Mining, Crude-Oil Production',
       'Apparel', 'Wholesalers: Diversified', 'Miscellaneous',
       'Utilities: Gas and Electric', 'Tobacco', 'Food Services',
       'Computer Peripherals', 'Oil and Gas Equipment, Services',
       'Metals', 'Packaging, Containers', 'Railroads',
       'Scientific,Photographic and Control Equipment',
       'Automotive Retailing, Services', 'Medical Products and Equipment',
       'Temporary Help', 'Engineering, Construction',
       'Advertising, marketing', 'Energy', 'Hotels, Casinos, Resorts',
       'Diversified Outsourcing Services', 'Financial Data Services',
       'Transportation and Logistics', 'Waste Management', 'Securities',
       'Publishing, Printing', 'Home Equipment, Furnishings',
       'Real estate', 'Homebuilders', 'Forest and Paper Products',
       'Trucking, Truck Leasing', 'Transportation Equipment',
       'Building Materials, Glass', 'Education'], dtype=object)

In [46]:
df['Industry'].nunique()

73